title: Alex James Lee. Academic Research in Environmental Politics.
short_title: Alex Lee
description:
baseurl:
url: "https://alexjameslee.co.uk"
permalink: "/:path/"
sass:
    sass_dir: _sass
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  posts:
    output: true
  campaigns:
    output: true
    permalink: "/campaigns/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-spaceship
